In [1]:
import spinOps
import numpy as np

spinOps.clebsch(.5,.5,.5,.5,1,1)

1.0

In [2]:
spinOps.clebsch(.5,.5,.5,-.5,0,0)

0.7071067811865476

In [3]:
spinsTimesTwo=[1,1]
spinOps.numberOfStates(spinsTimesTwo)
spinOps.createTLM(1,0,1, spinsTimesTwo)


array([[-0.5+0.j,  0. +0.j,  0. +0.j,  0. +0.j],
       [ 0. +0.j, -0.5+0.j,  0. +0.j,  0. +0.j],
       [ 0. +0.j,  0. +0.j,  0.5+0.j,  0. +0.j],
       [ 0. +0.j,  0. +0.j,  0. +0.j,  0.5+0.j]])

In [4]:
spinsTimesTwo=[3]
spinOps.numberOfStates(spinsTimesTwo)
spinOps.createTLM(3,0,0, spinsTimesTwo)


array([[-0.47434165+0.j,  0.        +0.j,  0.        +0.j,
         0.        +0.j],
       [ 0.        +0.j,  1.42302495+0.j,  0.        +0.j,
         0.        +0.j],
       [ 0.        +0.j,  0.        +0.j, -1.42302495+0.j,
         0.        +0.j],
       [ 0.        +0.j,  0.        +0.j,  0.        +0.j,
         0.47434165+0.j]])

In [5]:
spinOps.createRho2(1, .5)

array([0.08333333+0.j, 0.        +0.j, 0.40824829+0.j, 0.        +0.j,
       0.08333333+0.j])

In [6]:
spinOps.createRho1(1, .5)

array([0. +0.j, 1. +0.j, 0.5+0.j])

In [7]:
spinOps.wigner_d(2,0,0,np.pi/2)

-0.5

In [8]:
spinOps.DLM(2, 0, 0, np.pi/2,np.pi/2,np.pi/2)

SyntaxError: closing parenthesis ')' does not match opening parenthesis '{' (37039561.py, line 1)